- name: pull updated image
  hosts: all
  vars:
    ansible_python_interpreter: "/home/bhavil/Desktop/Employee_Management_System_SPEFinalProject/.venv/bin/python"
  pre_tasks:
    - name: Check Minikube's status.
      command: minikube status
      register: minikube_status
      changed_when: false
      ignore_errors: true
    - name: Start Minikube if it's not running.
      command: minikube start --vm-driver=docker --cpus 4 --memory 9152
      when: "not minikube_status.stdout or 'Running' not in minikube_status.stdout"
    - name: "Create a Python virtual environment"
      command: python3 -m venv ./ /home/bhavil/Desktop/Employee_Management_System_SPEFinalProject/.venv
      args:
        creates: /home/bhavil/Desktop/Employee_Management_System_SPEFinalProject/.venv      
    - name: "Install kubernetes python package"
      pip:
        name: kubernetes
        virtualenv: /home/bhavil/Desktop/Employee_Management_System_SPEFinalProject/.venv
        state: present
  tasks:
    - name: Delete any existing mongo deployment
      kubernetes.core.k8s:
        src: /home/bhavil/Desktop/Employee_Management_System_SPEFinalProject/k8s/mongodb.yaml
        state: absent
        namespace: default
    - name: Create a deployment for mongo
      kubernetes.core.k8s:
        src: /home/bhavil/Desktop/Employee_Management_System_SPEFinalProject/k8s/mongodb.yaml
        state: present
        apply: true
        namespace: default
    
    # - name: Wait for namespace to be active
    #   command: kubectl get namespace default -o jsonpath='{.status.phase}'
    #   register: namespace_status
    #   until: namespace_status.stdout == "Active"
    #   retries: 10
    #   delay: 5

    

    - name: Wait for MongoDB service to be ready
      command: kubectl wait --for=condition=available --timeout=60s deployment/mongodb -n default

    - name: Delete any existing deployment of Backend Deployment
      kubernetes.core.k8s:
        src: /home/bhavil/Desktop/Employee_Management_System_SPEFinalProject/k8s/backend.yaml
        state: absent
        namespace: default
    - name: Create a deployment for Backend Service
      kubernetes.core.k8s:
        src: /home/bhavil/Desktop/Employee_Management_System_SPEFinalProject/k8s/backend.yaml
        state: present
        apply: true
        namespace: default
    - name: Delete any existing deployment of Frontend Deployment
      kubernetes.core.k8s:
        src: /home/bhavil/Desktop/Employee_Management_System_SPEFinalProject/k8s/frontend.yaml
        state: absent
        namespace: default
    - name: Create a deployment for Frontend Service
      kubernetes.core.k8s:
        src: /home/bhavil/Desktop/Employee_Management_System_SPEFinalProject/k8s/frontend.yaml
        state: present
        apply: true
        namespace: default
    # - name: Delete any existing deployment of Filebeat
    #   kubernetes.core.k8s:
    #     src: /home/bhavil/Desktop/Employee_Management_System_SPEFinalProject/k8s/file-beat-config.yaml
    #     state: absent
    #     namespace: default
    # - name: Create a deployment for Filebeat
    #   kubernetes.core.k8s:
    #     src: /home/bhavil/Desktop/Employee_Management_System_SPEFinalProject/k8s/file-beat-config.yaml
    #     state: present
    #     apply: true
    #     namespace: default
    - name: Delete any existing deployment of Logstash
      kubernetes.core.k8s:
        src: /home/bhavil/Desktop/Employee_Management_System_SPEFinalProject/k8s/logstash.yaml
        state: absent
        namespace: default
    - name: Create a deployment for Logstash
      kubernetes.core.k8s:
        src: /home/bhavil/Desktop/Employee_Management_System_SPEFinalProject/k8s/logstash.yaml
        state: present
        apply: true
        namespace: default