# services:
#   backend:
#     build: ./backend
#     ports:
#       - "5050:5050" 
#     networks:
#       - mern_network
#     environment:
#       MONGO_URI: mongodb://mongo:27017/mydatabase  
#     depends_on:
#       - mongodb

#   frontend:
#     build: ./frontend
#     ports:
#       - "5173:5173"  
#     networks:
#       - mern_network
#     environment:
#       REACT_APP_API_URL: http://backend:5050 

#   mongodb:
#     image: mongo:latest  
#     ports:
#       - "27017:27017"  
#     networks:
#       - mern_network
#     volumes:
#       - mongo-data:/data/db  

# networks:
#   mern_network:
#     driver: bridge 

# volumes:
#   mongo-data:
#     driver: local  # Persist MongoDB data locally
  


# ===================================================================================================================
# ===================================================================================================================


services:
  backend:
    build: ./backend
    ports:
      - "5050:5050" 
    networks:
      - mern_network
    environment:
      MONGO_URI: mongodb://mongo:27017/  
    depends_on:
      - mongodb
      - elasticsearch  # Add Elasticsearch dependency for logging/search integration if needed

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "5173:5173"
  #   networks:
  #     - mern_network
  #   environment:
  #     VITE_API_URL: http://backend:5050 

  mongodb:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db  

  elasticsearch:
    image: elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.monitoring.enabled=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
      # - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - "9200:9200"  # Elasticsearch HTTP
      - "9300:9300"  # Elasticsearch transport
    networks:
      - mern_network
    volumes:
      - es_data:/usr/share/elasticsearch/data

  logstash:
    image: logstash:8.10.2
    container_name: logstash
    ports:
      - "5044:5044"
    networks:
      - mern_network
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.10.2
    container_name: kibana
    environment:
    - XPACK_SECURITY_ENABLED=false
    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - mern_network
    depends_on:
      - elasticsearch

networks:
  mern_network:
    driver: bridge 

volumes:
  mongo-data:
    driver: local  # Persist MongoDB data locally
  es_data:
    driver: local  # Persist Elasticsearch data locally

# ========================================================================
# ========================================================================

# services:
#   backend:
#     build: ./backend
#     ports:
#       - "5050:5050" 
#     networks:
#       - mern_network
#     environment:
#       MONGO_URI: mongodb://mongo:27017/mydatabase  
#     depends_on:
#       - mongodb
#       - elasticsearch

#   frontend:
#     build: ./frontend
#     ports:
#       - "5173:5173"
#     networks:
#       - mern_network
#     environment:
#       REACT_APP_API_URL: http://backend:5050 

#   mongodb:
#     image: mongo:latest  
#     ports:
#       - "27017:27017"  
#     networks:
#       - mern_network
#     volumes:
#       - mongo-data:/data/db  

#   elasticsearch:
#     image: elasticsearch:8.10.2
#     container_name: elasticsearch
#     environment:
#       - discovery.type=single-node
#       - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
#       - xpack.security.enabled=false
#     ports:
#       - "9200:9200"  # Elasticsearch HTTP
#       - "9300:9300"  # Elasticsearch transport
#     networks:
#       - mern_network
#     volumes:
#       - es_data:/usr/share/elasticsearch/data
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1

#   logstash:
#     image: logstash:8.10.2
#     container_name: logstash
#     ports:
#       - "5044:5044"
#     networks:
#       - mern_network
#     volumes:
#       - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
#     depends_on:
#       - elasticsearch

#   kibana:
#     image: kibana:8.10.2
#     container_name: kibana
#     environment:
#       - XPACK_SECURITY_ENABLED=false
#       - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#     ports:
#       - "5601:5601"
#     networks:
#       - mern_network
#     depends_on:
#       - elasticsearch

#   metricbeat:
#     image: docker.elastic.co/beats/metricbeat:8.10.2
#     container_name: metricbeat
#     user: root
#     depends_on:
#       - elasticsearch
#     networks:
#       - mern_network
#     volumes:
#       - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
#       - ./modules.d:/usr/share/metricbeat/modules.d:ro
#       - /var/run/docker.sock:/var/run/docker.sock
#       - /proc:/hostfs/proc:ro
#       - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
#       - /:/hostfs:ro
#     command: ["--strict.perms=false"]
# networks:
#   mern_network:
#     driver: bridge 

# volumes:
#   mongo-data:
#     driver: local  # Persist MongoDB data locally
#   es_data:
#     driver: local  # Persist Elasticsearch data locally