# apiVersion: v1
# kind: Namespace
# metadata:
#   name: mern-stack
# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: elasticsearch
#   namespace: mern-stack
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: elasticsearch
#   template:
#     metadata:
#       labels:
#         app: elasticsearch
#     spec:
#       containers:
#         - name: elasticsearch
#           image: elasticsearch:8.10.2
#           ports:
#             - containerPort: 9200
#             - containerPort: 9300
#           env:
#             - name: discovery.type
#               value: single-node
#             - name: ES_JAVA_OPTS
#               value: "-Xms1g -Xmx1g"
#           volumeMounts:
#             - name: es-data
#               mountPath: /usr/share/elasticsearch/data
#       volumes:
#         - name: es-data
#           persistentVolumeClaim:
#             claimName: es-pvc
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: elasticsearch
#   namespace: mern-stack
# spec:
#   ports:
#     - port: 9200
#     - port: 9300
#   selector:
#     app: elasticsearch

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: es-pvc
#   namespace: mern-stack
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  # namespace: mern-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:8.10.2
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms1g -Xmx1g"
            - name: xpack.security.enrollment.enabled
              value: "false"  # Enable enrollment for Kibana
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: es-data
          persistentVolumeClaim:
            claimName: es-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  # namespace: mern-stack
spec:
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: transport
      port: 9300
      targetPort: 9300
  selector:
    app: elasticsearch
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pvc
  # namespace: mern-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
