# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: bhavil13/ems-spe_fp-frontend:latest
        ports:
        - containerPort: 5173
        env:
        - name: REACT_APP_API_URL
          # value: http://backend:5050
          value: http://192.168.49.2:30050
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  ports:
  - port: 5173
    targetPort: 5173
    nodePort: 30173
  selector:
    app: frontend
