# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: frontend
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: frontend
#   template:
#     metadata:
#       labels:
#         app: frontend
#     spec:
#       containers:
#         - name: frontend
#           image: bhavil13/ems-spe_fp-frontend
#           ports:
#             - containerPort: 5173
#           env:
#             - name: REACT_APP_API_URL
#               value: http://backend:5050
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend
# spec:
#   ports:
#     - port: 5173
#   selector:
#     app: frontend

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: bhavil13/ems-spe_fp-frontend
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_URL
              value: http://backend:5050
          # resources:
          #   requests:
          #     cpu: "100m"        # 100 milli-CPU units (0.1 CPU)
          #     memory: "128Mi"     # 128MB of memory
          #   limits:
          #     cpu: "500m"         # 500 milli-CPU units (0.5 CPU)
          #     memory: "512Mi"     # 512MB of memory, delete these 4 comments when showing without hpa
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - port: 5173
  selector:
    app: frontend