apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  # namespace: mern-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: kibana:8.10.2
          ports:
            - containerPort: 5601
          env:
            - name: XPACK_SECURITY_ENABLED
              value: "false"
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch:9200"
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  # namespace: mern-stack
spec:
  ports:
    - port: 5601
  selector:
    app: kibana
