apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  # namespace: mern-stack
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
      }
      stdout { codec => rubydebug }  # Log events to console for debugging
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  # namespace: mern-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: logstash:8.10.2
          ports:
            - containerPort: 5044
          volumeMounts:
            - name: logstash-config
              mountPath: /usr/share/logstash/pipeline
              subPath: logstash.conf
      volumes:
        - name: logstash-config
          configMap:
            name: logstash-config
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  # namespace: mern-stack
spec:
  ports:
    - port: 5044
      targetPort: 5044
  selector:
    app: logstash
